# Generated by Django 5.1.2 on 2024-11-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_teacher', '0001_initial'),
        ('department', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dept_id',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='department.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.school'),
        ),
    ]
