# Generated by Django 5.1.2 on 2024-10-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='depart_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
