# Generated by Django 5.1.2 on 2024-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('maths_marks', models.FloatField()),
                ('chemistry_marks', models.FloatField()),
                ('physics_marks', models.FloatField()),
                ('total_marks', models.FloatField(blank=True, editable=False, null=True)),
                ('percentage', models.FloatField(blank=True, editable=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
