# Generated by Django 5.1.2 on 2024-10-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_student_progress', '0001_initial'),
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_teacher.teacher'),
        ),
    ]
