# Generated by Django 5.1.2 on 2024-10-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='depart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
