# Generated by Django 5.1.2 on 2024-11-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='chemistry_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='maths_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='physics_marks',
        ),
    ]
