# Generated by Django 5.1.2 on 2024-10-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0004_student_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='employee_id',
        ),
    ]
