# Generated by Django 5.1.2 on 2024-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0005_remove_student_class_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='performance',
            field=models.FloatField(default=0.0),
        ),
    ]
