# Generated by Django 5.1.2 on 2024-10-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0006_student_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='performance',
        ),
        migrations.AddField(
            model_name='teacher',
            name='performance',
            field=models.FloatField(default=0.0),
        ),
    ]
