# Generated by Django 5.1.2 on 2024-10-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0007_remove_student_performance_teacher_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='employee_id',
            new_name='emp_id',
        ),
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_marks',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
