# Generated by Django 5.1.2 on 2024-10-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0010_student_created_on_student_updated_on_and_more'),
        ('department', '0002_department_created_on_department_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_teacher', to='department.department'),
        ),
    ]
