# Generated by Django 5.1.2 on 2024-10-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0011_alter_teacher_department'),
        ('department', '0002_department_created_on_department_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='depart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='department.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_teacher', to='department.department'),
        ),
    ]
