# Generated by Django 5.1.2 on 2024-10-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0012_remove_teacher_department_teacher_depart_id_and_more'),
        ('department', '0003_alter_department_hod'),
        ('school', '0002_school_created_on_school_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='hod',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AddField(
            model_name='teacher',
            name='sc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='depart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
