# Generated by Django 5.1.2 on 2024-10-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
