# Generated by Django 5.1.2 on 2024-11-12 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('religion', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
