# Generated by Django 5.1.2 on 2024-11-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastercodes', '0002_mastercode_parent_code'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='caste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_caste', to='mastercodes.mastercode'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_education', to='mastercodes.mastercode'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_gender', to='mastercodes.mastercode'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_income', to='mastercodes.mastercode'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_profession', to='mastercodes.mastercode'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_religion', to='mastercodes.mastercode'),
        ),
    ]
