# Generated by Django 5.1.2 on 2024-11-12 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('bio', models.TextField(blank=True)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('family_details', models.TextField(blank=True)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('deactivate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
