# Generated by Django 5.1.2 on 2024-10-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0012_remove_teacher_department_teacher_depart_id_and_more'),
        ('department', '0002_department_created_on_department_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hod', to='app_student_progress.teacher'),
        ),
    ]
