# Generated by Django 5.1.2 on 2024-10-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student_progress', '0013_remove_teacher_hod_remove_teacher_school_and_more'),
        ('department', '0003_alter_department_hod'),
        ('school', '0002_school_created_on_school_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dept_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='school',
        ),
        migrations.AddField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='sc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.school'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_student_progress.teacher'),
        ),
    ]
