# Generated by Django 5.1.2 on 2024-10-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_rename_name_department_dept_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
    ]
