# Generated by Django 5.1.2 on 2024-11-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastercodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercode',
            name='parent_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mastercodes.mastercode'),
        ),
    ]
